# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Catch The Moments"
description: > # this means to ignore newlines until "email:"
   Video Making Contest

email: mathew.george@shcollege.ac.in
#blog logo
logo: "/assets/images/shc3.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/shcbg5.jpg"

name: 'Mathew George'
author: 'Mathew George'
#author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://matgeor.github.io" # the base hostname & protocol for your site
baseurl: "/heartian-frames"
#used to display twitter cards
twitter_handle: '@mathewgeorgem'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/mathewgeorgem
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/matgeor
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
